server:
  #ssl:
   #   key-password: changeit
    #  key-store: ${keystore_jks}
     # key-store-type: JKS
  #port: 8443
  port: 8888


spring:
  security:
    enabled: false
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kambalavijay/config-store.git
          default-label: main
          search-paths: '{application},{application}/{profile}'
          basedir: /Users/kvijay9/Desktop/sample-repo
          cloneOnStart: false
          skipSslValidation: true
          timeout: 20000
          username: kambalavijay
          password: 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
          force-pull: true
  profiles:
    active: dev

management:
  info:
    git:
      mode: simple  # To expose more git properties via /info endpoint, use "full" mode.
  #port: 8080
  #ssl:
   # enabled: false